languages:
  Ruby: false
  JavaScript: false
  Python: false
  PHP: false
engines:
 radon:
  enabled: true
 shellcheck:
   enabled: true
 markdownlint:
   enabled: true
ratings:
  paths:
    - "**.sh"
    - "**.md"
