version: '2'

services:
  nstat:
    image: intracom/nstat:cntrlpb
    privileged: true
    container_name: nstat
    hostname: nstat-node
    networks:
      nstat_net:
        ipv4_address: 172.17.0.10

  controller:
    image: intracom/nstat:cntrlpb
    privileged: true
    container_name: controller
    hostname: ctrl-node
    depends_on:
      - nstat
    networks:
      nstat_net:
        ipv4_address: 172.17.0.11

  mtcbench:
    image: intracom/nstat:cntrlpb
    privileged: true
    container_name: mtcbench
    hostname: mtcbench-node
    depends_on:
      - nstat
    networks:
      nstat_net:
        ipv4_address: 172.17.0.12

networks:
  nstat_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.17.0.0/24
        gateway: 172.17.0.1
