version: '2'

services:
  nstat:
    image: intracom/nstat:proxy
    privileged: true
    container_name: nstat
    hostname: nstat-node
    networks:
      nstat_net:
        ipv4_address: 10.0.1.10

  controller:
    image: intracom/nstat:cntrlpb
    privileged: true
    container_name: controller
    hostname: ctrl-node
    depends_on:
      - nstat
    networks:
      nstat_net:
        ipv4_address: 10.0.1.11

  mtcbench:
    image: intracom/mtcbench:proxy
    privileged: true
    container_name: mtcbench
    hostname: mtcbench-node
    depends_on:
      - nstat
    networks:
      nstat_net:
        ipv4_address: 10.0.1.12

networks:
  nstat_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
        gateway: 10.0.1.1
