version: '2'

services:
  nstat:
    image: intracom/nstat:proxy
    privileged: true
    container_name: nstat
    hostname: nstat-node
    networks:
      nstat_net:
        ipv4_address: 10.0.1.10
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000

  controller:
    image: intracom/nstat:controller_pb_proxy
    privileged: true
    container_name: controller
    hostname: ctrl-node
    depends_on:
      - nstat
    networks:
      nstat_net:
        ipv4_address: 10.0.1.11
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000

  mn01:
    image: intracom/multinet:proxy
    privileged: true
    container_name: mn-01
    hostname: mn01-node
    depends_on:
      - nstat
    networks:
      nstat_net:
        ipv4_address: 10.0.1.12
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000

  mn02:
    image: intracom/multinet:proxy
    privileged: true
    container_name: mn-02
    hostname: mn02-node
    depends_on:
      - nstat
    networks:
      nstat_net:
        ipv4_address: 10.0.1.13
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000

networks:
  nstat_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
        gateway: 10.0.1.1
